### PR TITLE
Add images with NVIDIA drivers

### PR DESCRIPTION
**Pull request by Plyrolith**
I wasn't able to build the images, since I don't have access to the private cosign key. Maybe you can merge this PR into its own branch and run a test build. I'll verify on my machine!

### CODE REVIEW

**Review by Sparkrai — APPROVED** [review]
Looks good to me

**Comment by Haxverse** [comment]
The KDE nvidia image will not get built due to the typo in the filename

**Comment by Plyrolith** [comment]
> The KDE nvidia image will not get built due to the typo in the filename

This seems to be a separate issue caused by conflicting requests for rpm-ostree.
The first failed build happened on main before the merge:
https://github.com/Sparkrai/bazzite-dx/actions/runs/12357714750/job/34486619293#step:4:4350

I'm checking if I can fix it, but I'll have to set up a branch with my own key to test building.

**Comment by Haxverse** [comment]
> > The KDE nvidia image will not get built due to the typo in the filename
> 
> This seems to be a separate issue caused by conflicting requests for rpm-ostree. The first failed build happened on main before the merge: https://github.com/Sparkrai/bazzite-dx/actions/runs/12357714750/job/34486619293#step:4:4350
> 
> I'm checking if I can fix it, but I'll have to set up a branch with my own key to test building.

https://github.com/Sparkrai/bazzite-dx/actions/runs/12359573502/job/34492606776#step:4:2028
https://github.com/Sparkrai/bazzite-dx/blob/4da40971b5ebdeb393226eb9d9cb8461a0b5e37e/recipes/bazzite-dx-nivida.yml

**Pull request merged**
